=== sbdlv/Web-Mario-Kart-DS/karts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="karts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kart" type="kart" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="kart">
        <xs:sequence>
            <xs:element name="propietario" type="xs:string"></xs:element>
            <xs:element name="nombre" type="xs:string"></xs:element>
            <xs:element name="velocidad" type="xs:integer"></xs:element>
            <xs:element name="aceleracion" type="xs:integer"></xs:element>
            <xs:element name="peso" type="xs:integer"></xs:element>
            <xs:element name="manejo" type="xs:integer"></xs:element>
            <xs:element name="drift" type="xs:integer"></xs:element>
            <xs:element name="items" type="xs:integer"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== sbdlv/Web-Mario-Kart-DS/xml/karts.xml
<?xml version="1.0" encoding="UTF-8"?>
<karts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="karts.xsd">
    <kart>
        <propietario>Mario</propietario>
        <nombre>B Dasher</nombre>
        <velocidad>58</velocidad>
        <aceleracion>69</aceleracion>
        <peso>41</peso> 
        <manejo>52</manejo>
        <drift>55</drift>
        <items>100</items>
    </kart>
    <kart>
        <propietario>Mario</propietario>
        <nombre>Standard MR</nombre>
        <velocidad>64</velocidad>
        <aceleracion>72</aceleracion>
        <peso>32</peso> 
        <manejo>56</manejo>
        <drift>57</drift>
        <items>66</items>
    </kart>
    <kart>
        <propietario>Mario</propietario>
        <nombre>Shooting Star</nombre>
        <velocidad>67</velocidad>
        <aceleracion>74</aceleracion>
        <peso>14</peso> 
        <manejo>60</manejo>
        <drift>59</drift>
        <items>33</items>
    </kart>
    <kart>
        <propietario>Luigi</propietario>
        <nombre>Poltergust 4000</nombre>
        <velocidad>75</velocidad>
        <aceleracion>76</aceleracion>
        <peso>17</peso> 
        <manejo>77</manejo>
        <drift>33</drift>
        <items>33</items>
    </kart>
    <kart>
        <propietario>Luigi</propietario>
        <nombre>Standard LG</nombre>
        <velocidad>72</velocidad>
        <aceleracion>74</aceleracion>
        <peso>32</peso> 
        <manejo>73</manejo>
        <drift>32</drift>
        <items>66</items>
    </kart>
    <kart>
        <propietario>Luigi</propietario>
        <nombre>Streamliner</nombre>
        <velocidad>66</velocidad>
        <aceleracion>71</aceleracion>
        <peso>41</peso> 
        <manejo>69</manejo>
        <drift>30</drift>
        <items>100</items>
    </kart>
    <kart>
        <propietario>Peach</propietario>
        <nombre>Royale</nombre>
        <velocidad>41</velocidad>
        <aceleracion>69</aceleracion>
        <peso>44</peso> 
        <manejo>45</manejo>
        <drift>94</drift>
        <items>100</items>
    </kart>
    <kart>
        <propietario>Peach</propietario>
        <nombre>Standard PC</nombre>
        <velocidad>47</velocidad>
        <aceleracion>73</aceleracion>
        <peso>32</peso> 
        <manejo>48</manejo>
        <drift>97</drift>
        <items>66</items>
    </kart>
    <kart>
        <propietario>Peach</propietario>
        <nombre>Light Tripper</nombre>
        <velocidad>51</velocidad>
        <aceleracion>75</aceleracion>
        <peso>20</peso> 
        <manejo>51</manejo>
        <drift>100</drift>
        <items>33</items>
    </kart>
    <kart>
        <propietario>Yoshi</propietario>
        <nombre>Egg 1</nombre>
        <velocidad>59</velocidad>
        <aceleracion>91</aceleracion>
        <peso>14</peso> 
        <manejo>89</manejo>
        <drift>41</drift>
        <items>33</items>
    </kart>
    <kart>
        <propietario>Yoshi</propietario>
        <nombre>Standard YS</nombre>
        <velocidad>55</velocidad>
        <aceleracion>90</aceleracion>
        <peso>32</peso> 
        <manejo>84</manejo>
        <drift>39</drift>
        <items>66</items>
    </kart>
    <kart>
        <propietario>Yoshi</propietario>
        <nombre>Cucumber</nombre>
        <velocidad>49</velocidad>
        <aceleracion>88</aceleracion>
        <peso>38</peso> 
        <manejo>80</manejo>
        <drift>37</drift>
        <items>100</items>
    </kart>
    <kart>
        <propietario>Toad</propietario>
        <nombre>Mushmellow</nombre>
        <velocidad>43</velocidad>
        <aceleracion>87</aceleracion>
        <peso>17</peso> 
        <manejo>69</manejo>
        <drift>69</drift>
        <items>33</items>
    </kart>
    <kart>
        <propietario>Toad</propietario>
        <nombre>Standard TD</nombre>
        <velocidad>39</velocidad>
        <aceleracion>85</aceleracion>
        <peso>32</peso> 
        <manejo>65</manejo>
        <drift>67</drift>
        <items>66</items>
    </kart>
    <kart>
        <propietario>Toad</propietario>
        <nombre>4-Wheel Cradle</nombre>
        <velocidad>33</velocidad>
        <aceleracion>83</aceleracion>
        <peso>44</peso> 
        <manejo>61</manejo>
        <drift>64</drift>
        <items>100</items>
    </kart>
    <kart>
        <propietario>Donkey Kong</propietario>
        <nombre>Rambi Rider</nombre>
        <velocidad>74</velocidad>
        <aceleracion>44</aceleracion>
        <peso>47</peso> 
        <manejo>31</manejo>
        <drift>74</drift>
        <items>100</items>
    </kart>
    <kart>
        <propietario>Donkey Kong</propietario>
        <nombre>Standard DK</nombre>
        <velocidad>80</velocidad>
        <aceleracion>47</aceleracion>
        <peso>32</peso> 
        <manejo>34</manejo>
        <drift>77</drift>
        <items>66</items>
    </kart>
    <kart>
        <propietario>Donkey Kong</propietario>
        <nombre>Wildlife</nombre>
        <velocidad>84</velocidad>
        <aceleracion>50</aceleracion>
        <peso>23</peso> 
        <manejo>37</manejo>
        <drift>79</drift>
        <items>33</items>
    </kart>
    <kart>
        <propietario>Wario</propietario>
        <nombre>Brute</nombre>
        <velocidad>92</velocidad>
        <aceleracion>53</aceleracion>
        <peso>23</peso> 
        <manejo>51</manejo>
        <drift>49</drift>
        <items>33</items>
    </kart>
    <kart>
        <propietario>Wario</propietario>
        <nombre>Standard WR</nombre>
        <velocidad>88</velocidad>
        <aceleracion>50</aceleracion>
        <peso>32</peso> 
        <manejo>48</manejo>
        <drift>47</drift>
        <items>66</items>
    </kart>
    <kart>
        <propietario>Wario</propietario>
        <nombre>Dragonfly</nombre>
        <velocidad>82</velocidad>
        <aceleracion>46</aceleracion>
        <peso>47</peso> 
        <manejo>45</manejo>
        <drift>45</drift>
        <items>100</items>
    </kart>
    <kart>
        <propietario>Bowser</propietario>
        <nombre>Tyrant</nombre>
        <velocidad>90</velocidad>
        <aceleracion>25</aceleracion>
        <peso>50</peso> 
        <manejo>25</manejo>
        <drift>64</drift>
        <items>100</items>
    </kart>
    <kart>
        <propietario>Bowser</propietario>
        <nombre>Standard BW</nombre>
        <velocidad>96</velocidad>
        <aceleracion>30</aceleracion>
        <peso>32</peso> 
        <manejo>28</manejo>
        <drift>67</drift>
        <items>66</items>
    </kart>
    <kart>
        <propietario>Bowser</propietario>
        <nombre>Hurricane</nombre>
        <velocidad>100</velocidad>
        <aceleracion>34</aceleracion>
        <peso>29</peso> 
        <manejo>32</manejo>
        <drift>69</drift>
        <items>33</items>
    </kart>
    <kart>
        <propietario>Daisy</propietario>
        <nombre>Power Flower</nombre>
        <velocidad>58</velocidad>
        <aceleracion>61</aceleracion>
        <peso>35</peso> 
        <manejo>36</manejo>
        <drift>84</drift>
        <items>100</items>
    </kart>
    <kart>
        <propietario>Daisy</propietario>
        <nombre>Standard DS</nombre>
        <velocidad>64</velocidad>
        <aceleracion>64</aceleracion>
        <peso>32</peso> 
        <manejo>40</manejo>
        <drift>87</drift>
        <items>66</items>
    </kart>
    <kart>
        <propietario>Daisy</propietario>
        <nombre>Light Dancer</nombre>
        <velocidad>67</velocidad>
        <aceleracion>66</aceleracion>
        <peso>20</peso> 
        <manejo>43</manejo>
        <drift>90</drift>
        <items>33</items>
    </kart>
    <kart>
        <propietario>Dry Bones</propietario>
        <nombre>Banisher</nombre>
        <velocidad>25</velocidad>
        <aceleracion>97</aceleracion>
        <peso>35</peso> 
        <manejo>91</manejo>
        <drift>45</drift>
        <items>100</items>
    </kart>
    <kart>
        <propietario>Dry Bones</propietario>
        <nombre>Standard DB</nombre>
        <velocidad>31</velocidad>
        <aceleracion>99</aceleracion>
        <peso>32</peso> 
        <manejo>96</manejo>
        <drift>47</drift>
        <items>66</items>
    </kart>
    <kart>
        <propietario>Dry Bones</propietario>
        <nombre>Dry Bomber</nombre>
        <velocidad>34</velocidad>
        <aceleracion>100</aceleracion>
        <peso>26</peso> 
        <manejo>100</manejo>
        <drift>49</drift>
        <items>33</items>
    </kart>
    <kart>
        <propietario>Waluigi</propietario>
        <nombre>Gold Mantis</nombre>
        <velocidad>75</velocidad>
        <aceleracion>65</aceleracion>
        <peso>29</peso> 
        <manejo>60</manejo>
        <drift>59</drift>
        <items>33</items>
    </kart>
    <kart>
        <propietario>Waluigi</propietario>
        <nombre>Standard WL</nombre>
        <velocidad>72</velocidad>
        <aceleracion>63</aceleracion>
        <peso>32</peso> 
        <manejo>56</manejo>
        <drift>57</drift>
        <items>66</items>
    </kart>
    <kart>
        <propietario>Waluigi</propietario>
        <nombre>Zipper</nombre>
        <velocidad>66</velocidad>
        <aceleracion>59</aceleracion>
        <peso>35</peso> 
        <manejo>52</manejo>
        <drift>55</drift>
        <items>100</items>
    </kart>
    <kart>
        <propietario>ROB</propietario>
        <nombre>ROB-BLS</nombre>
        <velocidad>100</velocidad>
        <aceleracion>55</aceleracion>
        <peso>25</peso> 
        <manejo>69</manejo>
        <drift>28</drift>
        <items>33</items>
    </kart>
    <kart>
        <propietario>ROB</propietario>
        <nombre>Standard RB</nombre>
        <velocidad>96</velocidad>
        <aceleracion>53</aceleracion>
        <peso>32</peso> 
        <manejo>65</manejo>
        <drift>27</drift>
        <items>66</items>
    </kart>
    <kart>
        <propietario>ROB</propietario>
        <nombre>ROB-LGS</nombre>
